export function usePipelinePage() {
  return {
    STATUSES: [],
    STATUS_LABELS: {},
    filters: { q: "", status: "all", owner: "all", date: "" },
    setFilters: () => {},
    activeLead: null,
    setActiveLead: () => {},
    addStatus: null,
    newLead: { name: "", company: "", email: "" },
    setNewLead: () => {},
    editLead: null,
    setEditLead: () => {},
    showAddActivity: false,
    setShowAddActivity: () => {},
    newActivity: { type: "", title: "", notes: "", date: "" },
    setNewActivity: () => {},
    leads: [],
    isLoading: false,
    groupedColumns: {},
    addLeadMutation: { isPending: false, mutate: () => {} },
    updateLeadMutation: { isPending: false, mutate: () => {} },
    editLeadMutation: { isPending: false, mutate: () => {} },
    addActivityMutation: { isPending: false, mutate: () => {} },
    handleDragEnd: () => {},
    handleAddLead: () => {},
    handleCloseAddDialog: () => {},
    handleSubmitNewLead: () => {},
    handleCloseLeadDetail: () => {},
    handleEditLead: () => {},
    handleAddActivity: () => {},
    handleCloseEditLead: () => {},
    handleCloseAddActivity: () => {},
    handleSubmitEditLead: () => {},
    handleSubmitActivity: () => {},
  };
}
